monitor = ,preferred,auto,1
$mainMod = SUPER
exec-once = uwsm finalize
exec-once = bazzite-lab-shell
input {
    kb_layout = fr
    follow_mouse = 1
}
general {
    gaps_in = 5
    gaps_out = 12
    border_size = 2
}
bind = $mainMod, RETURN, exec, foot
bind = $mainMod, D, exec, fuzzel
bind = $mainMod, Q, killactive,
bind = $mainMod, F, fullscreen,
bind = $mainMod SHIFT, E, exec, uwsm stop
bind = $mainMod, H, movefocus, l
bind = $mainMod, L, movefocus, r
bind = $mainMod, J, movefocus, d
bind = $mainMod, K, movefocus, u
bind = $mainMod, M, exec, hyprmod
